### ISSUE TITLE
join-tiles is broken

### ISSUE THREAD

**Issue by balta2ar** [samdobson/image_slicer#1]
1. There is no `open_images_in` in image_slicer (EDIT: it's in helpers.py and it's called `open_images`).
2. You renamed `join_tiles` to `join` not everywhere.

**Comment by kayvax** [comment]
Even after cleaning open_images_in and join_tiles it is still bugged.

**Comment by enzyme69** [comment]
Yep, I confirm, join_tiles is still bugged from command line. Wonder if there is example to run this via Python. Need to investigate.... anybody care to fix this?

**Comment by samdobson** [comment]
It looks like people have been working on this in various forks - happy to review and merge a PR.

**Comment by chughts** [comment]
I am working on an app where the split is done by one app, and the join in another, on a different machine. So I need this fix. I have fixed the join code in my environment, but I would like to automate the build, and would like to be able to pick it up with a clean pip install.

I need to tidy up my code to make it more generic, but are you OK, with me creating a pull request with a fix? Or is there an alternative fix that you would prefer, which I can take, test and if required clean up?

**Comment by samdobson** [comment]
Many thanks for this @chughts - pull request has been merged.
