### ISSUE TITLE
Extension formet issue

### ISSUE THREAD

**Issue by naresh-nishad** [samdobson/image_slicer#11]
As i am sliceing image into 4 parts it work fine but when i want to save in bmp formet it gives me error.
MY CODE
import image_slicer
tiles=image_slicer.slice('55.bmp', 4,save=False)
image_slicer.save_tiles(tiles, directory='~/cake_slices',prefix='slice', ext='bmp')
ERROR i am getting: TypeError: save_tiles() got an unexpected keyword argument 'ext'
For more information i am using 0.2.0 version of image_slicer with python 3.6

**Comment by samdobson** [comment]
`ext='bmp'` should be `format='bmp'` (documentation has been fixed in https://github.com/samdobson/image_slicer/commit/a69610e8d8ec4656716aa91d3de559b6766e3a8b)
