### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by whenthesungoesdown** [samdobson/image_slicer#16]
import image_slicer
image_slicer.slice('face.png', 9)

This is my code.

aj@AJ:~/my files/Codes/Python$ python image_slicer.py 
Traceback (most recent call last):
  File "image_slicer.py", line 1, in <module>
    import image_slicer
  File "/home/aj/my files/Codes/Python/image_slicer.py", line 2, in <module>
    image_slicer.slice('face.png', 9)
AttributeError: 'module' object has no attribute 'slice'

this is the error on terminal.

**Comment by samdobson** [comment]
The python interpreter is probably attempting to import the wrong thing because the filename with your code (``image_slicer.py``) is the same as the name of module. Rename your file and try again.
