### ISSUE TITLE
Error to slice multi-channel image OSError: cannot identify image file 'XXX.tif'

### ISSUE THREAD

**Issue by AkhilJPatil** [samdobson/image_slicer#23]
Hello,

I am working with TIF satellite image files and plan to split them in smaller images of same size.

Able to split a large satellite image of size 10980*10980 in 900 equal square-shaped images using the command
`tiles = image_slicer.slice(fullPath,900, save=False)`
`fullPath` is path to a single-channel TIF image `G:\\sat-data\\20150809.tif'`

However when same command is given a 3-channel TIF image (of same size) as input then below error is thrown
`OSError: cannot identify image file 'G:\\Merged-Sat-Imgs\\20150809-merged.tif'`

Does image_slicer supports multi-channel images? Please suggest.

Thanks,
Akhil

**Comment by nikhilbyte** [comment]
You need to convert it to png/jpg first.
