### ISSUE TITLE
Join slices to a new images

### ISSUE THREAD

**Issue by BogoK** [samdobson/image_slicer#24]
Could you please add an example of joining the tiles back to an image, since the documentation has none?

**Comment by qaz0778899** [comment]
Same. The image_slicer.join does not work for me. The joined image is a white board.

**Comment by chughts** [comment]
Follow the thread for the pull request #20 for example code on how to use the join.

**Comment by samdobson** [comment]
#20 is indeed the place to look for now - have marked for inclusion in the docs.
