### ISSUE TITLE
save_tiles(format) not recognizing 'jpg'

### ISSUE THREAD

**Issue by czarinasy** [samdobson/image_slicer#29]
Not specifying the format defaults to saving png tiles. If `format = "png"` is explicitly stated, it is also able to save png tiles. However, if `format = "jpg"` is stated, I get the error `  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PIL/Image.py", line 2073, in save
    save_handler = SAVE[format.upper()]
KeyError: 'JPG'`.

**Comment by samdobson** [comment]
Hi there. Try ``JPEG``, that is the format specifier supported by the underlying image manipulation library.
