### ISSUE TITLE
To split an image vertically 

### ISSUE THREAD

**Issue by P-Rainbow** [samdobson/image_slicer#38]
Great tool!

Is there a way to split an image vertically into multiple parts? (the example shows an horizontal way)

For example the original image shows 5 cats, and I want to split the image into 5 small images (each shows 1 cat)

Thank you.

**Comment by MaisumAbbas** [comment]
Make row = 1 and col = yournumber

**Comment by P-Rainbow** [comment]
@MaisumAbbas , marvelous! Thank you for the help!
