### ISSUE TITLE
CLI always writes pngs

### ISSUE THREAD

**Issue by FreakTheMighty** [samdobson/image_slicer#4]
The CLI always write PNGs into the source directory, even when specifying an output format. For example, `slice-image original/R1.JPG  16 -f JPG -d ./tiles/` produces an series of pngs in `original`, and jpgs into `./tiles`.

**Comment by samdobson** [comment]
Thanks for the heads-up, much appreciated. This was fixed in https://github.com/samdobson/image_slicer/commit/98b70131d55b8d772f1acbfaf901e1c1b30a0628
