### ISSUE TITLE
Please unpin Pillow

### ISSUE THREAD

**Issue by robmarkcole** [samdobson/image_slicer#43]
## Use Case
*Please unpin Pillow as this can lead to dependency hell

## Solution
`requirements = ["Pillow>=7.2.0"]` - tested in a fork, no issue

## Alternatives
*Please describe any alternatives you've considered, even if you've dismissed them*

**Comment by samdobson** [comment]
Thanks, fixed in https://github.com/samdobson/image_slicer/commit/64ea460cff232d2d911387bbdc1f4703ca826c14 and will roll into next release.
